#!/usr/bin/env python3
"""
Writes packages/scheduling/src/zips.ts: the center of every ZIP code within
RADIUS miles of home, for estimating drive times between jobs.

Source: the Census Bureau's ZCTA Gazetteer (public domain), e.g.
https://www2.census.gov/geo/docs/maps-data/data/gazetteer/2024_Gazetteer/2024_Gaz_zcta_national.zip

  python3 tools/zips.py 2024_Gaz_zcta_national.txt [home_zip] [radius_miles]

TENANT: home and radius are Knock Em' Down's. See docs/multi-tenant.md.
"""
import math
import sys

path = sys.argv[1]
home = sys.argv[2] if len(sys.argv) > 2 else '63049'
radius = float(sys.argv[3]) if len(sys.argv) > 3 else 90

rows = {}
with open(path) as f:
    next(f)
    for line in f:
        p = line.split('\t')
        rows[p[0].strip()] = (float(p[5]), float(p[6]))

def miles(a, b):
    la1, lo1, la2, lo2 = map(math.radians, (*a, *b))
    h = math.sin((la2 - la1) / 2) ** 2 + math.cos(la1) * math.cos(la2) * math.sin((lo2 - lo1) / 2) ** 2
    return 3958.8 * 2 * math.asin(math.sqrt(h))

near = sorted(z for z, c in rows.items() if miles(rows[home], c) <= radius)
body = ';'.join(f'{z}:{rows[z][0]:.3f},{rows[z][1]:.3f}' for z in near)
with open('packages/scheduling/src/zips.ts', 'w') as out:
    out.write(
        '// Generated by tools/zips.py from the Census ZCTA Gazetteer. Do not edit.\n'
        f'// ZIP centers within {radius:g} miles of {home}: "zip:lat,lng;...".\n'
        f'export const HOME_ZIP = {home!r};\n'
        f'export const ZIPS = {body!r};\n'
    )
print(f'{len(near)} ZIPs within {radius:g} miles of {home}')
